<p style="text-align: justify; line-height: 1.5;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">Харилцагч таны бэлдэж ирсэн анхан шатны эх материалыг бид мэргэжлийн эх бэлтгэлийн программд оруулан өрж техник ажиллагаа болон гоо зүйн дизайны ажиллагаа хийдэг билээ.&nbsp;</span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-size: 
      14px;"><span style="font-family: 
        Arial, Helvetica, sans-serif;">Та хэвлүүлэх эхээ авч ирэхдээ дараах зүйлсийг анхаарна уу.</span></span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-size: 
      14px;"><span style="font-family: 
        Arial, Helvetica, sans-serif;"><strong>Текст</strong>/бичвэр/: Та цахим хэлбэрээр буюу Microsoft Word, Microsoft Excel зэрэг программ дээр бичиж шивсэн байх.&nbsp;</span></span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-size: 
      14px;"><span style="font-family: 
        Arial, Helvetica, sans-serif;"><strong>Зураг</strong>: Зураг хэлбэрээр авч ирэх ба бид таны авч ирсэн эхийг чанартайгаар сканердаж оруулах болно. Хэрвээ бэлнээр авч ирэх боломжгүй тохиолдолд сканердан цахим хэлбэрээр илгээх ба Facebook-ээр илгээсэн зургийн чанар мууддаг тул та имайл-ээр илгээх хэрэгтэй.</span></span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-size: 
      14px;"><span style="font-family: 
        Arial, Helvetica, sans-serif;">Зарим тохиолдолд бэлэн эх захиалгад оруулдаг хэдий ч мэргэжлийн бус хүний бэлдсэн эх нь огтлооны зай байхгүй, хэвлэлийн өнгө нь зөрүүтэй зэрэг алдаатай байдаг тул та аль болох ажлын задгай файлаа авч ирэхийг хичээгээрэй. Эхийн өргөтгөлөө сонгоход тань тусламж болгох үүднээс дэлгэрэнгүй тайлбар орууллаа.</span></span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-size: 
      14px;"><span style="font-family: 
        Arial, Helvetica, sans-serif;">&Ecirc;&icirc;&igrave;&iuml;&uuml;&thorn;&ograve;&aring;&eth;&egrave;&eacute;&iacute; &iuml;&eth;&icirc;&atilde;&eth;&agrave;&igrave;м &aacute;&iquest;&eth; &ordm;&ordm;&eth; &ordm;&ordm;&eth;&egrave;&eacute;&iacute; &icirc;&iacute;&ouml;&euml;&icirc;&atilde;&ograve;&icirc;&eacute; &oacute;&divide;&eth;&agrave;&agrave;&ntilde; &ocirc;&icirc;&eth;&igrave;&agrave;&ograve; &aacute;&oacute;&thorn;&oacute; &ldquo;&otilde;&yacute;&euml;&rdquo;- &atilde;&iquest;&eacute; &aacute;&icirc;&euml; &agrave;&euml;&egrave;&acirc;&agrave;&agrave; &ccedil;&oacute;&eth;&agrave;&atilde; &aacute;&oacute;&thorn;&oacute; &igrave;&yacute;&auml;&yacute;&yacute;&euml;&euml;&egrave;&eacute;&atilde; &otilde;&agrave;&auml;&atilde;&agrave;&euml;&agrave;&otilde;, &auml;&agrave;&igrave;&aelig;&oacute;&oacute;&euml;&agrave;&otilde; &aacute;&icirc;&euml;&icirc;&euml;&ouml;&icirc;&icirc;&atilde;&iquest;&eacute; &thorn;&igrave;. &Ocirc;&icirc;&eth;&igrave;&agrave;&ograve; &aacute;&iquest;&otilde;&yacute;&iacute; &ordm;&ordm;&eth; &ordm;&ordm;&eth;&egrave;&eacute;&iacute; &auml;&agrave;&acirc;&oacute;&oacute; &aacute;&agrave; &auml;&oacute;&ograve;&agrave;&atilde;&auml;&agrave;&euml;&ograve;&agrave;&eacute; &ograve;&agrave;&euml;&oacute;&oacute;&auml;&ograve;&agrave;&eacute; &aacute;&ordm;&atilde;&ordm;&ordm;&auml; &iacute;&egrave;&eacute;&ograve; 20-&egrave;&icirc;&auml; &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;&agrave;&agrave;&ntilde; &atilde;&icirc;&euml; &otilde;&yacute;&auml;ийг нь та бүхэндээ &ograve;&icirc;&acirc;&divide; &ograve;&agrave;&iacute;&egrave;лцуулъ&yuml;.</span></span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-size: 
      14px;"><span style="font-family: 
        Arial, Helvetica, sans-serif;">PSD. &Yacute;&iacute;&yacute; &iacute;&uuml; Photoshop-&ucirc;&iacute; &auml;&icirc;&ograve;&icirc;&icirc;&auml; &ntilde;&ograve;&agrave;&iacute;&auml;&agrave;&eth;&ograve; &ocirc;&icirc;&eth;&igrave;&agrave;&ograve; &aacute;&ordm;&atilde;&ordm;&ordm;&auml; &otilde;&agrave;&eth; &ouml;&agrave;&atilde;&agrave;&agrave;&iacute; (bitmap) &ccedil;&oacute;&eth;&atilde;&agrave;&agrave;&ntilde;, &aacute;&iquest;&eth;&yacute;&iacute; &ordm;&iacute;&atilde;&ordm;&ograve; (CMYK) &ccedil;&oacute;&eth;&atilde;&egrave;&eacute;&atilde; &otilde;&iquest;&eth;&ograve;&yacute;&euml; &auml;&yacute;&igrave;&aelig;&egrave;&aelig; &agrave;&euml;&uuml;&ocirc;&agrave; &ecirc;&agrave;&iacute;&agrave;&euml; &aacute;&icirc;&euml;&icirc;&iacute; &icirc;&iacute;&icirc;&euml;&ucirc;&iacute; &otilde;&oacute;&acirc;&uuml;&auml; &otilde;&yuml;&ccedil;&atilde;&agrave;&agrave;&eth;&atilde;&iquest;&eacute; &icirc;&euml;&icirc;&iacute; &auml;&agrave;&acirc;&otilde;&agrave;&eth;&atilde;&agrave; &aacute;&oacute;&thorn;&oacute; &auml;&agrave;&acirc;&otilde;&agrave;&eth;&atilde;&agrave; &aacute;&iquest;&eth; &iacute;&uuml; 24 &ntilde;&oacute;&acirc;&atilde;&agrave;&agrave;&eth; &agrave;&aelig;&egrave;&euml;&euml;&agrave;&otilde; &aacute;&icirc;&euml;&icirc;&igrave;&aelig;&ograve;&icirc;&eacute;. Сүүлийн үед InDesign программ дээр давхаргатай орж ирдэг болсон.</span></span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-size: 
      14px;"><span style="font-family: 
        Arial, Helvetica, sans-serif;">TIFF (Tagged Image File Format) &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;. TIFF &ocirc;&icirc;&eth;&igrave;&agrave;&ograve; &iacute;&uuml; &ordm;&auml;&ordm;&eth; &ograve;&oacute;&ograve;&igrave;&ucirc;&iacute; &ordm;&eth;&atilde;&ordm;&iacute; &otilde;&yacute;&eth;&yacute;&atilde;&ouml;&yacute;&yacute;&iacute;&auml; &iuml;&eth;&icirc;&atilde;&eth;&agrave;&igrave;м &otilde;&icirc;&icirc;&eth;&icirc;&iacute;&auml; &ccedil;&oacute;&eth;&atilde;&egrave;&eacute;&iacute; &igrave;&yacute;&auml;&yacute;&yacute;&euml;&yacute;&euml; &auml;&agrave;&igrave;&aelig;&oacute;&oacute;&euml;&agrave;&otilde; &atilde;&icirc;&euml; &ldquo;&otilde;&yacute;&euml;&rdquo; &aacute;&egrave;&euml;&yacute;&yacute;. &Yacute;&iacute;&yacute; &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;&ucirc;&iacute; &ordm;&ordm;&eth; &iacute;&yacute;&atilde; &auml;&agrave;&acirc;&oacute;&oacute; &ograve;&agrave;&euml; &iacute;&uuml; LZW (Lempel-Ziff-Welch) &otilde;&yacute;&igrave;&yacute;&yacute;&otilde; &igrave;&yacute;&auml;&yacute;&yacute;&euml;&yacute;&euml; &ouml;&icirc;&igrave;&otilde;&icirc;&ograve;&atilde;&icirc;&otilde; &agrave;&eth;&atilde;&ucirc;&iacute;&otilde;&agrave;&agrave; &ograve;&oacute;&ntilde;&euml;&agrave;&igrave;&aelig;&ograve;&agrave;&eacute;&atilde;&agrave;&agrave;&eth; &ocirc;&agrave;&eacute;&euml;&ucirc;н хэмжээг &agrave;&euml;&auml;&agrave;&atilde;&auml;&agrave;&euml;&atilde;&iquest;&eacute;&atilde;&yacute;&yacute;&eth; 20- 40% &iacute;&yuml;&atilde;&ograve;&eth;&oacute;&oacute;&euml;&agrave;&iacute; &oslash;&agrave;&otilde;&agrave;&aelig; &divide;&agrave;&auml;&auml;&agrave;&atilde;&ograve; &icirc;&eth;&oslash;&egrave;&iacute;&icirc;.&nbsp;</span></span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-size: 
      14px;"><span style="font-family: 
        Arial, Helvetica, sans-serif;">JPEG (Joint Photographic Expert Gruop &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;). М&yacute;&auml;&yacute;&yacute;&euml;&euml;&egrave;&eacute;&atilde; &auml;&yacute;&yacute;&auml; &ccedil;&yacute;&eth;&atilde;&yacute;&yacute;&eth; &oslash;&agrave;&otilde;&agrave;&otilde;ад зориулж JPEG &otilde;&yacute;&igrave;&yacute;&yacute;&otilde; &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;&ucirc;&atilde; &aacute;&icirc;&euml;&icirc;&acirc;&ntilde;&eth;&oacute;&oacute;&euml;&ntilde;&agrave;&iacute;. &Atilde;&yacute;&otilde;&auml;&yacute;&yacute; &ccedil;&oacute;&eth;&atilde;&egrave;&eacute;&iacute; &ocirc;&agrave;&eacute;&euml;&ucirc;&atilde; &otilde;&yacute;&igrave;&aelig;&yacute;&yacute;&atilde; 10-20 &auml;&agrave;&otilde;&egrave;&iacute; &oslash;&agrave;&otilde;&agrave;&otilde;&auml;&agrave;&agrave; &ccedil;&agrave;&eth;&egrave;&igrave; &ccedil;&iquest;&eacute;&euml;&egrave;&eacute;&atilde; &atilde;&yacute;&yacute;&auml;&atilde;&yacute;&yacute;&ntilde; &divide;&agrave;&iacute;&agrave;&eth;&ucirc;&iacute; &agrave;&euml;&auml;&agrave;&atilde;&auml;&agrave;&euml; &atilde;&agrave;&eth;&auml;&agrave;&atilde;. &Ntilde;&iquest;&iquest;&euml;&egrave;&eacute;&iacute; &iquest;&aring;&auml; JPEG2000 &atilde;&yacute;&auml;&yacute;&atilde; &ocirc;&agrave;&eacute;&euml; &ouml;&icirc;&igrave;&otilde;&icirc;&ograve;&atilde;&icirc;&iacute; &oslash;&agrave;&otilde;&agrave;&otilde; &oslash;&egrave;&iacute;&yacute; &ocirc;&icirc;&eth;&igrave;&agrave;&ograve; &atilde;&agrave;&eth;&ntilde;&agrave;&iacute; &aacute;&ordm;&atilde;&ordm;&ordm;&auml; &yacute;&iacute;&yacute; &iacute;&uuml; &aring;&eth;&egrave;&eacute;&iacute; JPEG-&egrave;&eacute;&atilde; &aacute;&icirc;&auml;&acirc;&icirc;&euml; &egrave;&euml;&iquest;&iquest; &agrave;&euml;&auml;&agrave;&agrave; &aacute;&agrave;&atilde;&agrave;&ograve;&agrave;&eacute; &otilde;&agrave;&auml;&atilde;&agrave;&euml;&auml;&agrave;&atilde; &auml;&yacute;&acirc;&oslash;&egrave;&euml;&ograve;&ograve;&yacute;&eacute; &oacute;&divide;&egrave;&eth; Photoshop 8,0-&auml; &otilde;&yacute;&eth;&yacute;&atilde;&euml;&yacute;&aelig; &yacute;&otilde;&yacute;&euml;&aelig;&yacute;&yacute;.&nbsp;</span></span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-size: 
      14px;"><span style="font-family: 
        Arial, Helvetica, sans-serif;">PNG (Portable Network Graphics) &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;. М&yacute;&auml;&yacute;&yacute;&euml;&euml;&egrave;&eacute;&atilde; &agrave;&euml;&auml;&agrave;&euml;&atilde;&iquest;&eacute; &oslash;&agrave;&otilde;&auml;&agrave;&atilde;&agrave;&agrave;&eth;&agrave;&agrave; &agrave;&euml;&auml;&agrave;&eth; &otilde;&iquest;&eth;&ograve;&ntilde;&yacute;&iacute; LZW-&egrave;&eacute;&atilde; &divide; &agrave;&eth;&auml;&agrave;&agrave; &icirc;&eth;&otilde;&egrave;&otilde;&icirc;&icirc;&eth; &aacute;&icirc;&euml;&ntilde;&icirc;&iacute; &iacute;&uuml; Deflate &atilde;&icirc;&eth;&egrave;&igrave;&ucirc;&atilde; &agrave;&oslash;&egrave;&atilde;&euml;&agrave;&auml;&agrave;&atilde;&ograve;&agrave;&eacute; &otilde;&icirc;&euml;&aacute;&icirc;&icirc;&ograve;&icirc;&eacute;. &Egrave;&iacute;&ograve;&aring;&eth;&iacute;&aring;&ograve;&egrave;&eacute;&iacute; &ccedil;&icirc;&eth;&egrave;&oacute;&euml;&agrave;&euml;&ograve;&ograve;&agrave;&eacute; &yacute;&iacute;&yacute; &ocirc;&icirc;&eth;&igrave;&agrave;&ograve; &iacute;&uuml; &auml;&icirc;&ograve;&eth;&icirc;&icirc; png8, png24 &otilde;&yacute;&igrave;&yacute;&yacute;&otilde; &otilde;&icirc;&cedil;&eth; &auml;&yacute;&auml; &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;&ograve;&agrave;&eacute; &aacute;&ordm;&atilde;&ordm;&ordm;&auml;, &ouml;&egrave;&ocirc;&eth; &iacute;&uuml; &ordm;&iacute;&atilde;&ordm;&iacute;&egrave;&eacute; &atilde;&iquest;&iacute;&egrave;&eacute; &aacute;&icirc;&euml;&icirc;&igrave;&aelig;&egrave;&ograve; &otilde;&yacute;&igrave;&aelig;&yacute;&yacute;&atilde; &ccedil;&agrave;&agrave;&otilde; &aacute;&agrave; png24 &iacute;&uuml; 256 &atilde;&eth;&agrave;&auml;иа&ouml;ы&iacute; &ntilde;&agrave;&agrave;&eth;&euml;&ucirc;&atilde; &auml;&yacute;&igrave;&aelig;&auml;&yacute;&atilde; &ograve;&oacute;&euml; &otilde;&agrave;&atilde;&agrave;&ntilde; &ograve;&oacute;&iacute;&atilde;&agrave;&euml;&agrave;&atilde; &euml;&icirc;&atilde;&icirc;&atilde; &yuml;&igrave;&agrave;&eth; &divide; &ocirc;&icirc;&iacute; &auml;&yacute;&yacute;&eth; &ograve;&agrave;&acirc;&uuml;&ntilde;&agrave;&iacute; &egrave;&aelig;&egrave;&euml; &otilde;&agrave;&eth;&agrave;&atilde;&auml;&agrave;&iacute;&agrave;.</span></span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-size: 
      14px;"><span style="font-family: 
        Arial, Helvetica, sans-serif;">EPS (Encapsulated PostScript) &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;. &Yacute;&iacute;&yacute; &iacute;&uuml; &ouml;&yacute;&atilde;&yacute;&iacute; &auml;&iquest;&eth;&ntilde;&euml;&yacute;&euml;, &acirc;&aring;&ecirc;&ograve;&icirc;&eth; &ccedil;&oacute;&eth;&agrave;&atilde;, &ograve;&aring;&ecirc;&ntilde;&ograve;&yacute;&iacute; &igrave;&yacute;&auml;&yacute;&yacute;&euml;&yacute;&euml; &aacute;&icirc;&euml;&icirc;&icirc;&auml; &oslash;&eth;&egrave;&ocirc;&ograve; &ograve;&yacute;&igrave;&auml;&yacute;&atilde;&euml;&yacute;&otilde; &ograve;&ordm;&auml;&egrave;&eacute;&atilde;&iquest;&eacute; &ograve;&ordm;&otilde;&ordm;&ordm;&eth;&ordm;&igrave;&aelig; &otilde;&icirc;&icirc;&eth;&icirc;&iacute;&auml; &igrave;&yacute;&auml;&yacute;&yacute;&euml;&yacute;&euml; &ntilde;&icirc;&euml;&egrave;&euml;&ouml;&icirc;&otilde; &otilde;&yacute;&euml; &aacute;&icirc;&euml;&auml;&icirc;&atilde;. &Icirc;&eth;&divide;&egrave;&iacute; &iquest;&aring;&egrave;&eacute;&iacute; &otilde;&yacute;&acirc;&euml;&yacute;&euml;&egrave;&eacute;&iacute; &iuml;&eth;&icirc;&ouml;&aring;&ntilde;&ntilde;ы&iacute; &ograve;&aring;&otilde;&iacute;&icirc;&euml;&icirc;&atilde;&egrave;&eacute;&iacute; &iquest;&iacute;&auml;&yacute;&ntilde; &iacute;&uuml; PostScript &ocirc;&icirc;&eth;&igrave;&agrave;&ograve; &aacute;&ordm;&atilde;&ordm;&ordm;&auml; &euml;&agrave;&ccedil;&aring;&eth;ы&iacute; &iuml;&eth;&egrave;&iacute;&ograve;&aring;&eth;&yacute;&yacute;&ntilde; &yacute;&otilde;&euml;&yacute;&yacute;&auml; &iuml;&euml;&icirc;&ograve;&ograve;&aring;&eth;, &ocirc;&icirc;&ograve;&icirc;&aacute;&oacute;&oacute;&euml;&atilde;&agrave;&euml;&ograve;&ucirc;&iacute; &agrave;&acirc;&ograve;&icirc;&igrave;&agrave;&ograve; &otilde;&iquest;&eth;&ograve;&yacute;&euml;&otilde; &igrave;&yacute;&eth;&atilde;&yacute;&aelig;&euml;&egrave;&eacute;&iacute; &aacute;&icirc;&euml;&icirc;&icirc;&auml; &otilde;&agrave;&atilde;&agrave;&ntilde; &igrave;&yacute;&eth;&atilde;&yacute;&aelig;&euml;&egrave;&eacute;&iacute; &aacute;&iquest;&otilde; &ograve;&ordm;&otilde;&ordm;&ordm;&eth;&ordm;&igrave;&aelig; &ccedil;&ordm;&acirc;&otilde;&ordm;&iacute; &yacute;&iacute;&yacute; &otilde;&yacute;&euml;&yacute;&yacute;&eth; &icirc;&eacute;&euml;&atilde;&icirc;&euml;&ouml;&auml;&icirc;&atilde;.</span></span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-size: 
      14px;"><span style="font-family: 
        Arial, Helvetica, sans-serif;">PDF (portable document format) &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;. PDF &ocirc;&icirc;&eth;&igrave;&agrave;&ograve; &iacute;&uuml; &iuml;&eth;&icirc;&atilde;&eth;&agrave;&igrave;&igrave; x&icirc;&icirc;&eth;&icirc;&iacute;&auml;&ucirc;&iacute; &ntilde;&icirc;&euml;&egrave;&euml;&ouml;&icirc;&icirc;&iacute;&ucirc; &otilde;&agrave;&igrave;&atilde;&egrave;&eacute;&iacute; &icirc;&eth;&divide;&egrave;&iacute; &iquest;&aring;&egrave;&eacute;&iacute; &ldquo;&otilde;&yacute;&euml;&rdquo; &aacute;&icirc;&euml;&ntilde;&icirc;&iacute; &aacute;&ordm;&atilde;&ordm;&ordm;&auml; Acrobat Reader &otilde;&yacute;&igrave;&yacute;&yacute;&otilde; &iuml;&eth;&icirc;&atilde;&eth;&agrave;м&igrave;&ucirc;&iacute; &ograve;&oacute;&ntilde;&euml;&agrave;&igrave;&aelig;&ograve;&agrave;&eacute;&atilde;&agrave;&agrave;&eth; PDF &ocirc;&agrave;&eacute;&euml;&ucirc;&atilde; &oacute;&iacute;&oslash;&auml;&agrave;&atilde;. PDF &iacute;&uuml; PostScript-&egrave;&eacute;&atilde; &aacute;&icirc;&auml;&acirc;&icirc;&euml; &egrave;&euml;&iquest;&iquest; &oslash;&oacute;&oacute;&eth;&otilde;&agrave;&eacute;, &iacute;&agrave;&eacute;&auml;&acirc;&agrave;&eth;&ograve;&agrave;&eacute;, &aacute;&agrave;&ntilde; &egrave;&euml;&iquest;&iquest; &ouml;&icirc;&igrave;&otilde;&icirc;&iacute; (&aelig;&egrave;&oslash;&yacute;&yacute; &iacute;&uuml;: 150 &Igrave;&aacute;&agrave;&eacute;&ograve; PostScript &ocirc;&agrave;&eacute;&euml;&ucirc;&atilde; Acrobat Distiller &iuml;&eth;&icirc;&atilde;&eth;&agrave;&igrave;&agrave;&agrave;&eth; &icirc;&eth;&oacute;&oacute;&euml;&agrave;&agrave;&auml; &atilde;&agrave;&eth;&atilde;&agrave;&otilde;&agrave;&auml; 50 &Igrave;&aacute;&agrave;&eacute;&ograve; PDF &ocirc;&agrave;&eacute;&euml; &aacute;&icirc;&euml;&ograve;&icirc;&euml; &aacute;&agrave;&atilde;&agrave;&ntilde;&agrave;&otilde; &aacute;&icirc;&euml; PDF PostScript &ocirc;&agrave;&eacute;&euml; &iacute;&uuml; 70 &Igrave;&aacute;&agrave;&eacute;&ograve; &ccedil;&agrave;&eacute; &yacute;&ccedil;&yacute;&euml;&iacute;&yacute;.). Энэхүү программ дээр засвар хийх боломжтой хэдийч төвөгтэй байдаг.</span></span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-size: 
      14px;"><span style="font-family: 
        Arial, Helvetica, sans-serif;">AI &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;. Adobe Illustrator-&ucirc;&iacute; &yacute;&iacute;&yacute; &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;&ucirc;&iacute; &iquest;&iacute;&auml;&yacute;&ntilde; &iacute;&uuml; &igrave;&ordm;&iacute; &euml; PostScript &aacute;&egrave;&euml;&yacute;&yacute;. Adobe Illustrator 8.0-&icirc;&icirc;&ntilde; &yacute;&otilde;&euml;&yacute;&iacute; PostScript Level 3-&ucirc;&atilde; &auml;&yacute;&igrave;&aelig;&auml;&yacute;&atilde; &aacute;&icirc;&euml;&ntilde;&icirc;&iacute;.</span></span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-size: 
      14px;"><span style="font-family: 
        Arial, Helvetica, sans-serif;">Indd &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;. Adobe Indesign-&ucirc;&iacute; &yacute;&iacute;&yacute; &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;&ucirc;&iacute; &iquest;&iacute;&auml;&yacute;&ntilde; &iacute;&uuml; &igrave;&ordm;&iacute; &euml; PostScript &aacute;&egrave;&euml;&yacute;&yacute;. Adobe Indesign программ дээр бэлдсэн эх өөр компьютер дээр очиж нээгдэхдээ Version таарахгүй, фонт танихгүй, зураг линкгүй болох тохиолдолд байдаг учир та эхээ заавал Package үүсгэн хадгалан дамжуулаарай.</span></span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-size: 
      14px;"><span style="font-family: 
        Arial, Helvetica, sans-serif;">Сdr &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;. Corel Draw программ дээр &ouml;&yacute;&atilde;&yacute;&iacute; &auml;&iquest;&eth;&ntilde;&euml;&yacute;&euml;, &acirc;&aring;&ecirc;&ograve;&icirc;&eth; &ccedil;&oacute;&eth;&agrave;&atilde; боловсруулах формат &aacute;&egrave;&euml;&yacute;&yacute;. Энэхүү программ дээр бэлдсэн эхээ зөөвөрлөх тохиолдолд бичвэрт ашигласан фонтыг заавал давхар хуулах шаардлагатай.</span></span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-size: 
      14px;"><span style="font-family: 
        Arial, Helvetica, sans-serif;">WMF (Windows MetaFile) &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;. Windows &iquest;&eacute;&euml;&auml;&euml;&egrave;&eacute;&iacute; &ntilde;&egrave;&ntilde;&ograve;&aring;&igrave;&ograve;&yacute;&eacute; &ocirc;&agrave;&eacute;&euml; (&ccedil;&oacute;&eth;&agrave;&atilde;) &ntilde;&icirc;&euml;&egrave;&euml;&ouml;&icirc;&otilde; &aacute;&icirc;&euml;&icirc;&igrave;&aelig; &aacute;&iquest;&eth;&auml;&iquest;&iquest;&euml;&aelig; &aacute;&oacute;&eacute; &ouml;&icirc;&eth;&ucirc;&iacute; &atilde;&agrave;&iacute;&ouml; PostScript &aacute;&oacute;&ntilde; &ocirc;&icirc;&eth;&igrave;&agrave;&ograve; &iacute;&uuml; Windows &igrave;&aring;&ograve;&agrave;&ocirc;&agrave;&eacute;&euml; &aacute;&oacute;&thorn;&oacute; WMF &aacute;&ordm;&atilde;&ordm;&ordm;&auml; &yacute;&iacute;&yacute; &iacute;&uuml; &ecirc;&icirc;&igrave;&iuml;&agrave;&ecirc;&ograve; &auml;&egrave;&ntilde;&ecirc;&yacute;&iacute;&auml; &ccedil;&oacute;&eth;&atilde;&egrave;&eacute;&iacute; &ouml;&icirc;&igrave;&icirc;&atilde; &igrave;&agrave;&yuml;&atilde;&agrave;&agrave;&eth; &egrave;&eth;&auml;&yacute;&atilde;, &icirc;&ocirc;&egrave;&ntilde;&egrave;&eacute;&iacute; &otilde;&yacute;&eth;&yacute;&atilde;&euml;&yacute;&yacute;&iacute;&auml; &agrave;&oslash;&egrave;&atilde;&euml;&agrave;&otilde;&agrave;&auml; &icirc;&eth;&euml;&oacute;&oacute;&euml;&oslash;&atilde;&iquest;&eacute; &ntilde;&agrave;&eacute;&iacute; &ograve;&agrave;&euml;&ograve;&agrave;&eacute; &divide;, &yacute;&otilde; &aacute;&yacute;&euml;&ograve;&atilde;&yacute;&euml;&egrave;&eacute;&iacute; &yuml;&acirc;&ouml;&agrave;&auml; &ordm;&iacute;&atilde;&egrave;&eacute;&atilde; &iacute;&uuml; &ordm;&ordm;&eth;&divide;&egrave;&euml;&aelig; &aacute;&icirc;&euml;&auml;&icirc;&atilde;&atilde;&iquest;&eacute;&atilde;&yacute;&yacute;&ntilde; &otilde;&yacute;&acirc;&euml;&yacute;&otilde; &ccedil;&icirc;&eth;&egrave;&oacute;&euml;&agrave;&euml;&ograve;&agrave;&agrave;&eth; &agrave;&oslash;&egrave;&atilde;&euml;&agrave;&otilde;&agrave;&auml; &ograve;&icirc;&otilde;&egrave;&eth;&icirc;&igrave;&aelig;&atilde;&iquest;&eacute;.&nbsp;</span></span></p>
<p style="text-align: justify; line-height: 1.5;"><span style="font-family: Arial, Helvetica, sans-serif; font-size: 14px;">DCS (Desktop Color Separation) &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;. &Yacute;&iacute;&yacute; &iacute;&uuml; EPS-&ucirc;&iacute; &iacute;&yacute;&atilde;&yacute;&iacute; &otilde;&oacute;&acirc;&egrave;&euml;&aacute;&agrave;&eth; &aacute;&ordm;&atilde;&ordm;&ordm;&auml; Quark Xpress-&egrave;&eacute;&iacute; &ordm;&iacute;&atilde;&ordm; &ntilde;&agrave;&euml;&atilde;&agrave;&ntilde;&agrave;&iacute; &ccedil;&oacute;&eth;&agrave;&atilde; &auml;&iquest;&eth;&ntilde;&euml;&yacute;&euml;&egrave;&eacute;&atilde; &auml;&yacute;&igrave;&aelig;&egrave;&otilde; &ccedil;&icirc;&eth;&egrave;&euml;&atilde;&icirc;&icirc;&eth; Quark &ecirc;&icirc;&igrave;&iuml;&agrave;&iacute;&egrave;&auml; &aacute;&icirc;&euml;&icirc;&acirc;&ntilde;&eth;&oacute;&oacute;&euml;&ntilde;&agrave;&iacute; &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;. DCS 1.0 &aacute;&agrave; 2.0 &atilde;&yacute;&aelig; &aacute;&egrave;&eacute; &aacute;&ordm;&atilde;&ordm;&ordm;&auml; &iacute;&agrave;&eacute;&eth;&oacute;&oacute;&euml;&ntilde;&agrave;&iacute; &ordm;&iacute;&atilde;&ordm; &agrave;&oslash;&egrave;&atilde;&euml;&agrave;&iacute; &ordm;&iacute;&atilde;&ordm; &ntilde;&agrave;&euml;&atilde;&agrave;&ntilde;&agrave;&iacute; &ouml;&yacute;&atilde;&yacute;&iacute; &auml;&iquest;&eth;&ntilde;&egrave;&eacute;&atilde; &otilde;&agrave;&auml;&atilde;&agrave;&euml;&agrave;&otilde; &iacute;&yacute;&atilde;&yacute;&iacute; &oslash;&egrave;&euml;&auml;&yacute;&atilde; &agrave;&eth;&atilde;&agrave; &aacute;&icirc;&euml;&icirc;&icirc;&auml; &aacute;&agrave;&eacute;&iacute;&agrave;. Photoshop &iuml;&eth;&icirc;&atilde;&eth;&agrave;&igrave;&auml; &ccedil;&oacute;&eth;&atilde;&egrave;&eacute;&atilde; CMYK Multichannel &ocirc;&icirc;&eth;&igrave;&agrave;&ograve; &aacute;&icirc;&euml;&atilde;&icirc;&icirc;&auml; &iquest;&iquest;&atilde;&yacute;&yacute;&eth; &otilde;&agrave;&auml;&atilde;&agrave;&euml;&iacute;&agrave;. &Otilde;&agrave;&eth;&egrave;&iacute; InDesign &iacute;&uuml; &otilde;&yacute;&acirc;&euml;&yacute;&euml;&egrave;&eacute;&iacute; &iquest;&iacute;&auml;&ntilde;&yacute;&iacute; 4 &ordm;&iacute;&atilde;&ordm; &auml;&yacute;&yacute;&eth; &iacute;&yacute;&igrave;&yacute;&yacute;&auml; spot color &aacute;&oacute;&thorn;&oacute; &iacute;&agrave;&eacute;&eth;&oacute;&oacute;&euml;&ntilde;&agrave;&iacute; &aacute;&oacute;&auml;&atilde;&egrave;&eacute;&atilde; &agrave;&oslash;&egrave;&atilde;&euml;&agrave;&iacute; &icirc;&euml;&icirc;&iacute; &ordm;&iacute;&atilde;&ordm;&ordm;&eth; &aacute;&yacute;&euml;&ograve;&atilde;&yacute;&ntilde;&yacute;&iacute; &yacute;&otilde;&yacute;&yacute; DCS2.0 &ocirc;&icirc;&eth;&igrave;&agrave;&ograve;&agrave;&agrave;&eth; &otilde;&agrave;&auml;&atilde;&agrave;&euml;&auml;&agrave;&atilde;.</span></p>